alias ll='ls -lAhGT'
alias grep='grep --color=auto'
alias python='python3'
alias weather='curl http://v2.wttr.in'
alias pip='pip3'
alias pip-upgrade-all='pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip3 install -U'
alias bounce_wifi='networksetup -setairportpower en0 off; networksetup -setairportpower en0 on'
alias gl='git log --graph --oneline --decorate'
alias gc='git add . && git commit'
alias branches='git branch -v'
alias listvms='VBoxManage list vms'
alias runningvms='VBoxManage list runningvms'
alias zshconfig="mate ~/.zshrc"
alias chk='f() { git checkout $1 };f'
export PATH="/usr/local/sbin:$PATH"
